shimoju/metabase-ruby

Gemfile.lock, docker-compose.yml, metabase.gemspec, spec/metabase/client_spec.rb, spec/spec_helper.rb, spec/vcr_cassettes/Metabase_Client/login/incorrect_username_or_password/raises_error.yml, spec/vcr_cassettes/Metabase_Client/login/success/returns_a_session_token.yml
webmockとvcrでAPIレスポンスをモックします。
リポジトリのdocker-compose.ymlで立ち上げたMetabaseコンテナにリクエストするようにしてあります。
=> Mock response

.travis.yml, spec/metabase/endpoint/session_spec.rb, spec/metabase/endpoint/user_spec.rb, spec/support/shared_contexts.rb
`Metabase::Client`はほぼすべてのテストで作ることになるのでshared_contextにしました。
=> Use shared_context

lib/metabase/endpoint.rb, lib/metabase/endpoint/card.rb, spec/metabase/endpoint/card_spec.rb, spec/spec_helper.rb, spec/vcr_cassettes/Metabase_Endpoint_Card/cards/success/returns_all_cards.yml
あとはもうエンドポイントをひたすら生やすだけなのでやっていきます。
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md
を見ると結構API多いし命名に悩むものもあるので、まずはほとんど悩む必要のない`GET /api/:resource`（`Client#resources`とする）だけを追加したファイルを作っていって、一周したらまた考えようかなと思います。
=> Add Metabase::Endpoint::Card

lib/metabase/endpoint.rb, lib/metabase/endpoint/alert.rb, spec/metabase/endpoint/alert_spec.rb, spec/vcr_cassettes/Metabase_Endpoint_Alert/alerts/success/returns_all_alerts.yml
ここらへんは何も考えずにがしがし追加していく
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#get-apialert
=> Add Metabase::Endpoint::Alert

lib/metabase/endpoint.rb, lib/metabase/endpoint/collection.rb, spec/metabase/endpoint/collection_spec.rb, spec/vcr_cassettes/Metabase_Endpoint_Collection/collections/success/returns_all_collections.yml
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#get-apicollection
=> Add Metabase::Endpoint::Collection

lib/metabase/endpoint.rb, lib/metabase/endpoint/dashboard.rb, spec/metabase/endpoint/dashboard_spec.rb, spec/vcr_cassettes/Metabase_Endpoint_Dashboard/dashboards/success/returns_all_dashboards.yml
gogo
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#get-apidashboard
=> Add Metabase::Endpoint::Dashboard

lib/metabase/endpoint.rb, lib/metabase/endpoint/database.rb, spec/metabase/endpoint/database_spec.rb, spec/vcr_cassettes/Metabase_Endpoint_Database/databases/success/returns_all_databases.yml
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#get-apidatabase
=> Add Metabase::Endpoint::Database

lib/metabase/endpoint.rb, lib/metabase/endpoint/metric.rb, spec/metabase/endpoint/metric_spec.rb, spec/vcr_cassettes/Metabase_Endpoint_Metric/metrics/success/returns_all_metrics.yml
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#get-apimetric
=> Add Metabase::Endpoint::Metric

lib/metabase/endpoint.rb, lib/metabase/endpoint/pulse.rb, spec/metabase/endpoint/pulse_spec.rb, spec/vcr_cassettes/Metabase_Endpoint_Pulse/pulses/success/returns_all_pulses.yml
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#get-apipulse
=> Add Metabase::Endpoint::Pulse

lib/metabase/endpoint.rb, lib/metabase/endpoint/card.rb, lib/metabase/endpoint/public.rb, spec/metabase/endpoint/card_spec.rb, spec/metabase/endpoint/public_spec.rb, spec/vcr_cassettes/Metabase_Endpoint_Card/card/success/returns_the_card.yml, spec/vcr_cassettes/Metabase_Endpoint_Public/public_card/success/returns_the_public_card.yml
`GET /api/public/card/:uuid`を追加します。
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#get-apipubliccarduuid
対応関係が変じゃないか確認するために`GET /api/card/:id`も追加しました。
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#get-apicardid
`client.card(card_id)`に対して`client.public_card(card_uuid)`になってて、これで良いんじゃないかと思います。
=> Add Metabase::Endpoint::Public

lib/metabase/endpoint.rb, lib/metabase/endpoint/revision.rb, spec/metabase/endpoint/revision_spec.rb, spec/vcr_cassettes/Metabase_Endpoint_Revision/revisions/success/returns_revisions_of_the_object.yml
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#get-apirevision
`card_revisions`や`dashboard_revisions`があると便利そうだけど、きりがなさそうなのでそういうのは後でかな〜
=> Add Metabase::Endpoint::Revision

lib/metabase/endpoint.rb, lib/metabase/endpoint/setup.rb, spec/metabase/endpoint/setup_spec.rb, spec/vcr_cassettes/Metabase_Endpoint_Setup/admin_checklists/success/returns_admin_checklists.yml
管理画面に出てくるチェックリストのAPIかー
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#get-apisetupadmin_checklist
=> Add Metabase::Endpoint::Setup

lib/metabase/endpoint.rb, lib/metabase/endpoint/x_ray.rb, spec/metabase/endpoint/x_ray_spec.rb, spec/vcr_cassettes/Metabase_Endpoint_XRay/x_ray_card/success/returns_x-ray_job.yml
これ何してくれるのかよくわからないな…job idしか返さないし…
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#get-apix-raycardid
`XRay`ってクラス名がめっちゃかっこいい
=> Add Metabase::Endpoint::XRay

Gemfile.lock
faradayが上がったぞ〜
https://github.com/lostisland/faraday/releases/tag/v0.15.2
=> bundle update 20180524

README.md
=> Remove fullwidth space

README.md, lib/metabase/endpoint/activity.rb, lib/metabase/endpoint/alert.rb, lib/metabase/endpoint/async.rb, lib/metabase/endpoint/card.rb, lib/metabase/endpoint/collection.rb, lib/metabase/endpoint/dashboard.rb, lib/metabase/endpoint/database.rb, lib/metabase/endpoint/metric.rb, lib/metabase/endpoint/permissions.rb, lib/metabase/endpoint/public.rb, lib/metabase/endpoint/pulse.rb, lib/metabase/endpoint/revision.rb, lib/metabase/endpoint/segment.rb, lib/metabase/endpoint/session.rb, lib/metabase/endpoint/setting.rb, lib/metabase/endpoint/setup.rb, lib/metabase/endpoint/table.rb, lib/metabase/endpoint/user.rb, lib/metabase/endpoint/util.rb, lib/metabase/endpoint/x_ray.rb, spec/metabase/endpoint/async_spec.rb, spec/vcr_cassettes/Metabase_Endpoint_Async/running_jobs/success/returns_all_running_jobs.yml
ここまでのメソッドにdoc commentを入れます。
`#running_jobs`が`Array<Integer>`を返すということを知った…
=> Add document

Gemfile.lock, lib/metabase/endpoint/activity.rb, lib/metabase/endpoint/alert.rb, lib/metabase/endpoint/async.rb, lib/metabase/endpoint/card.rb, lib/metabase/endpoint/collection.rb, lib/metabase/endpoint/dashboard.rb, lib/metabase/endpoint/database.rb, lib/metabase/endpoint/metric.rb, lib/metabase/endpoint/permissions.rb, lib/metabase/endpoint/public.rb, lib/metabase/endpoint/pulse.rb, lib/metabase/endpoint/revision.rb, lib/metabase/endpoint/segment.rb, lib/metabase/endpoint/session.rb, lib/metabase/endpoint/setting.rb, lib/metabase/endpoint/setup.rb, lib/metabase/endpoint/table.rb, lib/metabase/endpoint/user.rb, lib/metabase/endpoint/util.rb, lib/metabase/endpoint/x_ray.rb, lib/metabase/version.rb
=> Add method description

lib/metabase/endpoint/user.rb
Post request added to create a user. params remain the same.
=> Method added to create user 

.travis.yml
=> Update CI Ruby version

Gemfile.lock, metabase.gemspec
=> faraday >= 0.8
